# Generated by Django 5.0.1 on 2024-01-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_gallery', '0002_remove_song_artist_audio_artist_audio_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
